### PR TITLE
ENHANCEMENT Support nested object types

### LINKED ISSUE #13: Question regarding nested objects
At the moment Searchable::getReferenceSearchableFields() will "flatten" related objects into separate sets of multvalue fields (each field a list of that fields value for the given relation).

However what I really need is the ability to create nested objects to allow us to do complex sort behaviour.

E.g.

instead of my document looking as:

```json
{
  "OpenHomes_StartDateTime": [
    "2018-05-31T12:00:00",
    "2018-06-02T12:15:00"
  ],
  "OpenHomes_EndDateTime": [
    "2018-05-31T12:25:00",
    "2018-06-02T12:45:00"
  ]
}
```

It needs to look like:

```json
{
  "OpenHomes": [
    {
      "StartDateTime": "2018-05-31T12:00:00",
      "EndDateTime": "2018-05-31T12:25:00"
    },
    {
      "StartDateTime": "2018-06-02T12:15:00",
      "EndDateTime": "2018-06-02T12:45:00"
    }
  ]
}
```

Can you tell me how this is possible?

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #13

Summary of changes:
 - New support for `type: nested` for relations. See https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-mapping.html and  https://www.elastic.co/guide/en/elasticsearch/reference/5.6/nested.html for reference
 - Resolved a huge amount of code duplication issues, broke up large blocks into smaller methods, and consolidated a lot of logic that wasn't being applied consistently (e.g. dbfield -> elasticsearch field typing).
- Exceptions are now thrown and not eaten if no logger is specified. This was causing real errors to be hidden away letting the user think there was no issue.
- Fixed some backwards logic in ElasticaPercolateService
- Indexes can now be deleted with deleteIndex() in case a rebuild is necessary.
- Code cleanup, fix linting, psr2, phpdoc, etc

### CODE REVIEW

**Comment by tractorcow** [comment]
I've fixed the merge conflicts. I've also added in a bug fix for empty dates not being caught.

**Comment by tractorcow** [comment]
I've started working on a batch API; Let me know if you want this in another PR. I'll just use this branrch for the time being. ;)

**Comment by stevie-mayhew** [comment]
@shane-garelja, @timhiggs or @bendubuisson any chance of getting this merged for @tractorcow? 

We'd be happy to take over maintenance of this if you prefer, as we're using it extensively!

**Comment by tractorcow** [comment]
I much prefer to invest in elasticsearch than Solr to be honest. ;)

**Comment by shane-nzer** [comment]
> @shane-garelja, @timhiggs or @bendubuisson any chance of getting this merged for @tractorcow?
> 
> We'd be happy to take over maintenance of this if you prefer, as we're using it extensively!

@stevie-mayhew - have added you as a collaborator. Hope this helps. We don't seem to be able to get to it unfortunately.

**Comment by stevie-mayhew** [comment]
Thanks @shane-garelja :)

**Comment by tractorcow** [comment]
I've stripped out the batch importer API into another branch. I'll PR this separately to keep PRs better defined.

**Comment by tractorcow** [comment]
Due to changes in API (e.g. setValue made public -> protected) this PR will need a new major version.

**Comment by tractorcow** [comment]
I've broken the batch API into a new PR at https://github.com/heyday/silverstripe-elastica/pull/17

**Comment by stevie-mayhew** [comment]
Will wait for #17 before tagging new versions

**Comment by bendubuisson** [comment]
outstanding work guys, thank you!

**Pull request merged**
